In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/mpg.csv")

In [3]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [4]:
df = df.drop("name", axis=1
             )

In [5]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin  
0          70    usa  
1          70    usa  
2          70    usa  
3          70    usa  
4          70    usa

In [6]:
df.origin.value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [ ]:
#transofrmamos en numeros

In [7]:
def origin(x):
    if x== "usa": 
        return 1
    else: 
        return 0

In [8]:
df["origin"] = df.origin.apply(origin)

In [9]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year  origin  
0          70       1  
1          70       1  
2          70       1  
3          70       1  
4          70       1

In [11]:
X = df.drop("mpg", axis=1)
y = df.mpg

In [15]:
pip install scikit-learn


  Using cached scikit_learn-1.5.0-cp310-cp310-macosx_12_0_arm64.whl.metadata (11 kB)
  Using cached scipy-1.13.1-cp310-cp310-macosx_12_0_arm64.whl.metadata (60 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.5.0-cp310-cp310-macosx_12_0_arm64.whl (11.0 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached scipy-1.13.1-cp310-cp310-macosx_12_0_arm64.whl (30.3 MB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Note: you may need to restart the kernel to use updated packages.


In [47]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import Pipeline

In [17]:
norm = MinMaxScaler()
norm.fit(X)
X_sc = norm.transform(X)

In [19]:
params = {"max_depth": [3,5,7,9], "n_estimators":[100,200,300]}
rf = RandomForestRegressor()

grid = RandomizedSearchCV(
    estimator=rf,
    param_distributions=params,
    n_iter= 200,
    cv=3,
    n_jobs=-1
)

grid.fit(X_sc,y)

/Users/cescrosello/miniconda3/envs/api_env/lib/python3.10/site-packages/sklearn/model_selection/_search.py:320: UserWarning: The total space of parameters 12 is smaller than n_iter=200. Running 12 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


RandomizedSearchCV(cv=3, estimator=RandomForestRegressor(), n_iter=200,
                   n_jobs=-1,
                   param_distributions={'max_depth': [3, 5, 7, 9],
                                        'n_estimators': [100, 200, 300]})

In [20]:
grid.best_score_

0.6065141474395147

In [21]:
grid.best_estimator_.score(X_sc,y)

0.9672101959382572

In [22]:
#ya tenemos el modelo, lo guardamos

In [27]:
import pickle
with open("model.pkl", "wb") as f:
    pickle.dump(grid.best_estimator_, f)

In [28]:
with open("model.pkl", "rb") as f:
    saved_model = pickle.load(f)

In [ ]:
#vamos a probar una prediccion

In [ ]:
#©reamos datos nuevos

In [33]:
X_sc[0,:]

array([1.        , 0.61757106, 0.45652174, 0.5361497 , 0.23809524,
       0.        , 1.        ])

In [ ]:
#al modelo para predecir le tenemos que pasar los datos normalizados

In [34]:
pred_df = pd.DataFrame(np.array([1.        , 0.61757106, 0.45652174, 0.5361497 , 0.23809524,
       0.        , 1.      ]).reshape(1,-1),columns = X.columns)

In [35]:
saved_model.predict(pred_df)

/Users/cescrosello/miniconda3/envs/api_env/lib/python3.10/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(


array([16.93374725])

In [36]:
y.head(1)

0    18.0
Name: mpg, dtype: float64

In [37]:
norm

MinMaxScaler()

In [38]:
dir(norm)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_reset',
 '_sklearn_auto_wrap_output_keys',
 '_validate_data',
 '_validate_params',
 'clip',
 'copy',
 'data_max_',
 'data_min_',
 'data_range_',
 'feature_names_in_',
 'feature_range',
 '

In [39]:
#para poder meter el modelo en una app, tenemos que incluirle la parte de normalizacion de los datos

In [42]:
norm.data_max_
#estos son los valores maximos de cada columna

array([8.00e+00, 4.55e+02, 2.30e+02, 5.14e+03, 2.48e+01, 8.20e+01,
       1.00e+00])

In [41]:
norm.data_min_
#esto son los valores minimos de una columna

array([   3.,   68.,   46., 1613.,    8.,   70.,    0.])

In [43]:
with open ("norm.pkl", "wb") as f: 
    pickle.dump(norm,f)

In [44]:
with open ("norm.pkl", "rb") as f: 
    saved_norm = pickle.load(f)

In [45]:
pred_df = pd.DataFrame(np.array([8,307,130,3504, 12, 70, 1 ]).reshape(1,-1),columns = X.columns)

In [46]:
saved_norm.transform(pred_df)

array([[1.        , 0.61757106, 0.45652174, 0.5361497 , 0.23809524,
        0.        , 1.        ]])

In [ ]:
#esta es otra forma, guardando el normalizador  y aplicarlo  a los nuevos datos antes de predecir

In [51]:
pipe = Pipeline([("norm", MinMaxScaler()),( "rf", RandomForestRegressor(n_jobs=-1))])

params = {"max_depth": [3,5,7,9], "n_estimators":[100,200,300]}

grid = RandomizedSearchCV(
    estimator=pipe,
    param_distributions=params,
    n_iter= 200,
    cv=3,
    n_jobs=-1
)

grid.fit(X,y)

ValueError: Invalid parameter 'n_estimators' for estimator Pipeline(steps=[('norm', MinMaxScaler()),
                ('rf', RandomForestRegressor(n_jobs=-1))]). Valid parameters are: ['memory', 'steps', 'verbose'].

In [ ]:
#montamos la base de datos SQLite

In [54]:
from sqlalchemy import create_engine
import sqlite3

In [55]:
churro = "sqlite:///mpgdb.db"

In [56]:
engine = create_engine (churro)

In [60]:
inputs = str(pred_df.values[0])

In [61]:
outputs = saved_model.predict(pred_df)[0]

/Users/cescrosello/miniconda3/envs/api_env/lib/python3.10/site-packages/sklearn/base.py:486: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(


In [64]:
from datetime import datetime

In [65]:
date = str(datetime.now())[0:19]

In [67]:
log_df = pd.DataFrame({"inputs":[inputs], "outputs":[outputs], "date": [date]})

In [70]:
log_df.to_sql("logs", con = engine, if_exists = "append", index = None)

1

In [71]:
pd.read_sql("SELECT * FROM logs", con = engine)

inputs    outputs                 date
0  [   8  307  130 3504   12   70    1]  16.168786  2024-06-10 10:23:11